services:
  # Backend API service
  - type: web
    name: whatsthat-api
    env: python
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.7
    healthCheckPath: /
    autoDeploy: true

  # Frontend static site
  - type: web
    name: whatsthat-frontend
    env: static
    buildCommand: bun run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
