services:
  - type: web
    name: whats-that-again
    env: python
    # No buildCommand - let startCommand handle everything
    startCommand: /bin/bash ./start.sh
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NPM_VERSION
        value: 10.2.4
    healthCheckPath: /
    autoDeploy: true
